# https://github.com/pulsar256/vindriktning_esphome#vindriktning-pm25-sensor-custom-sensor

esphome:
  name: ikea-vindriktning
  platform: ESP8266
  board: d1_mini
  includes:
    - vindriktning_esphome/components/vindriktning/vindriktning.h

uart:
  id: uart_bus
  tx_pin: D0
  rx_pin: D2
  baud_rate: 9600

sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new VindriktningSensor(id(uart_bus));
    App.register_component(my_sensor);
    return {my_sensor};
  sensors:
    name: "IKEA vindriktning PM2.5 sensor"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
      static_ip: 192.168.1.14
      gateway: 192.168.1.1
      subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ikea-vindriktning Hotspot"
    password: "UrVPORnMjCt4"

captive_portal:

logger:

api:

ota:
