esphome:
  name: vanocni_retez_1
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Vanocni retez 1"
    pin: D2
    restore_mode: ALWAYS_ON
