esphome:
  name: water-meter-cold

esp32:
  board: nodemcu-32s
  # recommended for the BLE proxy but no compatible with webserver/prometheusa :(
  #framework:
  #  type: esp-idf
  #  version: recommended

bluetooth_proxy:
  active: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:

# To get data to Grafana (eventually)
web_server:

prometheus:

# old config
sensor:
  - platform: pulse_counter
    pin: GPIO16
    name: "Water Cold"
    unit_of_measurement: "l/min"
    id: water_cold_pulse_counter
    icon: "mdi:water"
    accuracy_decimals: 0
    total:
      name: 'Water Cold Total'
      unit_of_measurement: "m³"
      id: water_cold_total
      accuracy_decimals: 3
      device_class: water
      state_class: total_increasing
      filters:
        - multiply: 0.001
